<?php

/**
 * @file
 * Module file for umd_schoolwide_header module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function umd_schoolwide_header_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.umd_schoolwide_header':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      } else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_page().
 *
 * Adds js to the page.
 */
function umd_schoolwide_header_preprocess_page(&$variables)
{
  $config = \Drupal::config('system.theme');   
  $default_theme = $config->get('default');
  $core_greater_than_11 = version_compare(\Drupal::VERSION, '11.0', '>=');

  // Only load library on FE pages, as well as not load if umd_terp theme in use, whuich already loads this lib.
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  } else {
    // For themnes other than umd_terp, or versions of umd_terp for less than core v 11.0, add UMD library
    if($default_theme !== 'umd_terp' || $core_greater_than_11 == FALSE) {
      $variables['#attached']['library'][] = 'umd_schoolwide_header/umd_header';
    }
  }
}

function umd_schoolwide_header_page_top(array &$page_top)
{
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  } else {
    $markup = umd_schoolwide_header_build_header();
    $page_top['umd_schoolwide_header'] = [
      '#type' => 'inline_template',
      '#template' => $markup
    ];
  }
}

/**
 * Custom Function.
 *
 * Builds HTML markup for header.
 */
function umd_schoolwide_header_build_header()
{
  $umd_schoolwide_header_fields = \Drupal::config('umd_schoolwide_header.settings');
  // Get config fields, so we can modify markup accordingly.
  $hide_events = $umd_schoolwide_header_fields->get('umd_schoolwide_header.hide_events');
  $hide_news = $umd_schoolwide_header_fields->get('umd_schoolwide_header.hide_news');
  $hide_admissions = $umd_schoolwide_header_fields->get('umd_schoolwide_header.hide_admissions');
  $hide_giving = $umd_schoolwide_header_fields->get('umd_schoolwide_header.hide_giving');
  $hide_schools = $umd_schoolwide_header_fields->get('umd_schoolwide_header.hide_schools');
  $hide_search = $umd_schoolwide_header_fields->get('umd_schoolwide_header.hide_search');

  $markup = '<umd-element-navigation-utility';

  // Events
  if ($hide_events !== 1) {
    $markup .= ' data-events="true"';
  }

  // News
  if ($hide_news !== 1) {
    $markup .= ' data-news="true"';
  }

  // Admissions
  if ($hide_admissions !== 1) {
    $markup .= ' data-admissions="true"';
  }

  // Giving
  if ($hide_giving !== 1) {
    $markup .= ' data-gift="true"';
  }

  // Colleges & Schools
  if ($hide_schools !== 1) {
    $markup .= ' data-schools="true"';
  }

  // Search
  if ($hide_search !== 1) {
    $markup .= ' data-search="true"';
  } 

  // Standardized components
  $markup .= ' data-alert-url="https://umd-main.production.servd.dev/api/v2"';
  $markup .= ' data-layout-lock="full"';
  $markup .= ' data-alert-off="false"';

  // Finalize Markup
  $markup .= '></umd-element-navigation-utility>';

  return $markup;
}